import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const Roboto_init = Roboto({
  subsets: ["latin"],
  weight: '500',
  variable: '--font-roboto'
});
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Roboto_init.variable}>{children}</body>
    </html>
  );
}
